# Generated by Django 3.0.8 on 2020-10-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
