# Generated by Django 3.1.2 on 2020-10-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.FloatField(blank=True),
        ),
    ]
