# Generated by Django 3.1.2 on 2020-11-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_quantity_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
