# Generated by Django 3.1.2 on 2020-11-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(),
        ),
    ]
