# Generated by Django 3.1.2 on 2020-11-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_likedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='save_later',
            field=models.BooleanField(default=False),
        ),
    ]
