# Generated by Django 3.1.2 on 2020-10-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201015_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Camino', 'En Camino'), ('Entregado', 'Entregado')], default='Pendiente', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
