# Generated by Django 3.0.8 on 2020-10-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='disccount',
        ),
    ]
