# Generated by Django 3.1.2 on 2020-11-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
