# Generated by Django 3.1.2 on 2020-11-21 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedproduct',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='store.listaliked'),
        ),
    ]
