# Generated by Django 3.0.8 on 2020-10-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_usuario_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_pic',
            field=models.ImageField(blank=True, default='usuario.png', null=True, upload_to=''),
        ),
    ]
