# Generated by Django 3.1.2 on 2020-11-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='porcentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
