# Generated by Django 3.1.2 on 2020-11-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_coupon_porcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dis',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
