# Generated by Django 3.1.2 on 2020-11-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20201124_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
