# Generated by Django 3.1.2 on 2020-11-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20201124_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disccount',
            field=models.BooleanField(default=False),
        ),
    ]
