# Generated by Django 3.1.2 on 2020-12-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20201130_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='original_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
