# Generated by Django 3.1.2 on 2020-12-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_orderproduct_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alta',
            field=models.BooleanField(default=False),
        ),
    ]
