# Generated by Django 3.1.2 on 2020-12-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_product_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='original_price',
            field=models.FloatField(null=True),
        ),
    ]
