# Generated by Django 3.1.2 on 2020-12-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_product_num_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alta',
            field=models.BooleanField(default=False),
        ),
    ]
